### PR TITLE
Added my name to contributors and updated index School card section

### PR DESCRIPTION
**Pull request by ebitsdev**

### CODE REVIEW

**Comment by jaredrileysmith** [comment]
Looks good to me!

**Comment by jamesperrin** [comment]
1. At the moment, pull requests will only be approved for project Team members.
2. Student cards will be populated by a data source, thus not requiring anyone to submit cards.
3. There will be a Google form made available for everyone to submit their information.

**Comment by ebitsdev** [comment]
Ok, thanks. Will there be any role for us to play? I had requested to be added for code review or test. Will be that be possible?

**Comment by jamesperrin** [comment]
Yes, there will be room for code reviews and testing. But, that is still a couple weeks out. Keep an eye on the forum.

**Pull request closed without merging**
