### PR TITLE
updating Yearbook page

### PR DESCRIPTION
**Pull request by SoteroX**
Update includes a list of all students on yearbook page along with the option to search for students by name

### CODE REVIEW

**Comment by SoteroX** [comment]
Whenever my laptop finish repairing Ill take a look. Might have to refork your code with the new updated commits that you just added and than have leafdragon make another commit to my fork, or have leafdragon just make a pull request straight to your code

**Comment by sgs006** [comment]
Thanks!

**Comment by jamesperrin** [comment]
Okay, I went through the PR and the yearbook.html file line-by-line.

@SoteroX you will need to update your files, it doesn't match yours exactly, but it has all your functionality.

Everyone else, you need to update your versions, this will eliminate further conflicts.
**Tip:** Each time you sit down to work, you should check your local working files match the main repository.

Thanks,
JP

**Comment by SoteroX** [comment]
What would be the best way to update?

**Comment by SoteroX** [comment]
Would it be with 
git fetch upstream

**Comment by jamesperrin** [comment]
I always use these commands. (Thanks @beckybair )
```
git fetch upstream
git merge upstream/master
```

**Pull request merged**
