### PR TITLE
Added footer to all pages

### PR DESCRIPTION
**Pull request by adrianacervantes**
Footer is added to all pages and styled

### CODE REVIEW

**Comment by sgs006** [comment]
This does not work properly when I test the page. The footer jumps to the middle of the page instead of the bottom. Can someone more familiar with bootstrap help out with this one?

**Comment by tecmie** [comment]
has this been fixed yet, does anyone have a screenshot

**Comment by jamesperrin** [comment]
I can get with @adrianacervantes to review.

**Comment by sgs006** [comment]
From what I can tell the footer is not in the right div. But also, it is saying something about the JS so I don't want to touch it haha.

**Comment by sgs006** [comment]
I thought I fixed it but this is the result 
image

**Comment by sgs006** [comment]
The index.html file definitely has the wrong wrong code in the footer section and the footer seems to be in there two times. I'm off work, but i'll be back later

**Pull request closed without merging**
