### PR TITLE
Made a few changes

### PR DESCRIPTION
**Pull request by chrisvneal**
Hey all, no one answered me so I assumed this project was still "open source", here is just some commits to refactor CSS, handle minor issues like removing reboot.css since it it is already included in Bootstrap, and cleaned up a lot of _dirty_ code that was lying around. If you don't include that's ok. Thanks for starting the project, it looks really fun!

### CODE REVIEW

**Comment by chrisvneal** [comment]
Also, I am not done everything. There is still the hamburger menu icon on large display so I haven't hooked that up to anything.

**Comment by chrisvneal** [comment]
Added a bit of jQuery to add some style to the resources page section and set an "interface" of sorts splitting the navigational menu and group items.

resources

**Comment by chrisvneal** [comment]
If you all didn't mind, I removed the fixed style from the footer because there's really non relevant information to keep prominent like that so it should stay put.

Also the best I could I gave _index.html_ an "over the fold" style look

overthefold

**Comment by chrisvneal** [comment]
I put fixed positioning back on footer, sorry. Does look rather nice 

footersback

**Comment by chrisvneal** [comment]
I removed the 100% search on focus just to neaten up the area. We can easily add the styles back if you want the feature. I figured a simple search tool on the left side would fit for the page..

searchbar

**Comment by chrisvneal** [comment]
The menu _(on mobile)_ could be styled better with smoother effects, but it is **fully functional**!

**Comment by jamesperrin** [comment]
Please only make pull requests for work you have been assigned. By submitting work that you were not assigned is robbing an opportunity from another Team Member, which is not nice or fair.

Refer: https://discussions.udacity.com/t/udacity-yearbook-student-project-fe-team-home-page/610818/54

**Pull request closed without merging**
